name: SBAHypixelify
version: ${project.version}
main: org.pronze.hypixelify.Hypixelify
api-version: "1.13"
depend: [BedWars]
softdepend: [PlaceholderAPI, Citizens, ProtocolLib]
author: pronze

commands:
  bwaddon:
    description: bwaddon
    usage: /<command>
  party:
    description: party system
    usage: /<command>
    aliases: [p]