name: SBAHypixelify
version: ${project.version}
main: org.pronze.hypixelify.Hypixelify
api-version: "1.13"
depend: [BedWars,ProtocolLib]
softdepend: [PlaceholderAPI]
author: pronze

commands:
  bwaddon:
    description: bwaddon
    usage: /<command>