name: SBAHypixelify
version: ${project.version}
main: org.pronze.hypixelify.Hypixelify
api-version: "1.13"
depend: [BedWars]
softdepend: [PlaceholderAPI, Citizens, Parties]
author: pronze

commands:
  bwaddon:
    description: bwaddon
    usage: /<command>